Languages = {
    version : '版本',
    loading : '加载中...',
    progressMsg : '正在下载 {1} 中的 {0}',
    location : '地点',
    popupWin : '弹出窗口',
    error: '错误',
    UnableToConnect: '不能连接; 请稍后再尝试！',
    networkError: '网络不可用，请确认您已连接上互联网！',
    noWebService: '没有网络服务器，请先指定网络服务器！',
    downloadComplete: '文件已下载完毕！',
    downloadFail : '下载失败，文件找不到！',
    downloadConfirm : '你确定要下载PDF文档吗？',
    downloadConfirmTitle : '下载PDF文档',
    ptrPull : '下拉刷新...',
    ptrRelease : '释放刷新...',
    ptrUpating : '更新中...',
    switchLang:'转换语言',
    updateAvailable: "有新的更新",
    downloadUpdate: "请下载此应用的最新版本。\r\n点击\"取消\"将不再提醒！",
    newUpdateHasDownloaded: "更新內容已下载完毕！",
    ok:"確定",
    cancel:"取消"
};
module.exports = Languages;
