Languages = {
	version : '版本',
	loading : '加载中...',
    progressMsg : '正在下載 {1} 中的 {0}',
	location : '地點',
	popupWin : '彈出窗口',
    error: '錯誤',
    UnableToConnect: '不能連接; 請稍後再嘗試！',
    networkError: '網絡不可用，請確認您已連接上互聯網！',
    noWebService: '沒有網絡服務器，請先指定網絡服務器！',
    downloadComplete: '文件已下載完畢！',
    downloadFail : '下載失敗，文件找不到！',
    downloadConfirm : '你確定要下載PDF文檔嗎？',
    downloadConfirmTitle : '下載PDF文檔',
    ptrPull : '下拉刷新...',
    ptrRelease : '釋放刷新...',
    ptrUpating : '更新中...',
	switchLang:'轉換語言',
    updateAvailable: "有新的更新",
    downloadUpdate: "請下載此應用的最新版本。\r\n點擊\"取消\"將不再提醒！",
    newUpdateHasDownloaded: "更新內容已下載完畢！",
    ok:"確定",
    cancel:"取消"
};
module.exports = Languages;
